//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifs.Application.Enterp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifs.Application.Enterp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code part &amp;0 of company &amp;1 is not available or already occupied..
        /// </summary>
        public static string ERROR_CompCodePartNotAvailable {
            get {
                return ResourceManager.GetString("ERROR_CompCodePartNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes are entered by another user. Please reopen the window to view all notes..
        /// </summary>
        public static string ERROR_NotesExist {
            get {
                return ResourceManager.GetString("ERROR_NotesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code part &amp;0 of template &amp;1 is not available or already occupied..
        /// </summary>
        public static string ERROR_TempCodePartNotAvailable {
            get {
                return ResourceManager.GetString("ERROR_TempCodePartNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Protected Persons.
        /// </summary>
        public static string HEAD_AccessToPerson {
            get {
                return ResourceManager.GetString("HEAD_AccessToPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Existing Customer.
        /// </summary>
        public static string HEAD_CopyCustomer {
            get {
                return ResourceManager.GetString("HEAD_CopyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Existing Supplier.
        /// </summary>
        public static string HEAD_CopySupplier {
            get {
                return ResourceManager.GetString("HEAD_CopySupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string HEAD_DetailCompany {
            get {
                return ResourceManager.GetString("HEAD_DetailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string HEAD_DetailCustomerInfo {
            get {
                return ResourceManager.GetString("HEAD_DetailCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs.
        /// </summary>
        public static string HEAD_DetailCustomsInfo {
            get {
                return ResourceManager.GetString("HEAD_DetailCustomsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder.
        /// </summary>
        public static string HEAD_DetailForwarderInfo {
            get {
                return ResourceManager.GetString("HEAD_DetailForwarderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string HEAD_DetailManufacturerInfo {
            get {
                return ResourceManager.GetString("HEAD_DetailManufacturerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string HEAD_DetailOwnerInfo {
            get {
                return ResourceManager.GetString("HEAD_DetailOwnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string HEAD_DetailSupplierInfo {
            get {
                return ResourceManager.GetString("HEAD_DetailSupplierInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string HEAD_OverviewCompany {
            get {
                return ResourceManager.GetString("HEAD_OverviewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string HEAD_OverviewCustomerInfo {
            get {
                return ResourceManager.GetString("HEAD_OverviewCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs List.
        /// </summary>
        public static string HEAD_OverviewCustomsInfo {
            get {
                return ResourceManager.GetString("HEAD_OverviewCustomsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarders.
        /// </summary>
        public static string HEAD_OverviewForwarderInfo {
            get {
                return ResourceManager.GetString("HEAD_OverviewForwarderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string HEAD_OverviewManufacturerInfo {
            get {
                return ResourceManager.GetString("HEAD_OverviewManufacturerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners.
        /// </summary>
        public static string HEAD_OverviewOwnerInfo {
            get {
                return ResourceManager.GetString("HEAD_OverviewOwnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string HEAD_OverviewPersonInfo {
            get {
                return ResourceManager.GetString("HEAD_OverviewPersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string HEAD_OverviewSupplierInfo {
            get {
                return ResourceManager.GetString("HEAD_OverviewSupplierInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Identities Series.
        /// </summary>
        public static string HEAD_PartyIdSeries {
            get {
                return ResourceManager.GetString("HEAD_PartyIdSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 - Column.
        /// </summary>
        public static string LAYOUT_C1 {
            get {
                return ResourceManager.GetString("LAYOUT_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2 - Column.
        /// </summary>
        public static string LAYOUT_C2 {
            get {
                return ResourceManager.GetString("LAYOUT_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code - Column.
        /// </summary>
        public static string LAYOUT_C3 {
            get {
                return ResourceManager.GetString("LAYOUT_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City - Column.
        /// </summary>
        public static string LAYOUT_C4 {
            get {
                return ResourceManager.GetString("LAYOUT_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State - Column.
        /// </summary>
        public static string LAYOUT_C5 {
            get {
                return ResourceManager.GetString("LAYOUT_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County - Column.
        /// </summary>
        public static string LAYOUT_C6 {
            get {
                return ResourceManager.GetString("LAYOUT_C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code - Column.
        /// </summary>
        public static string LAYOUT_C7 {
            get {
                return ResourceManager.GetString("LAYOUT_C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Offset.
        /// </summary>
        public static string LAYOUT_ColOffset {
            get {
                return ResourceManager.GetString("LAYOUT_ColOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog - Height.
        /// </summary>
        public static string LAYOUT_Height {
            get {
                return ResourceManager.GetString("LAYOUT_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 - Row.
        /// </summary>
        public static string LAYOUT_R1 {
            get {
                return ResourceManager.GetString("LAYOUT_R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2 - Row.
        /// </summary>
        public static string LAYOUT_R2 {
            get {
                return ResourceManager.GetString("LAYOUT_R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code - Row.
        /// </summary>
        public static string LAYOUT_R3 {
            get {
                return ResourceManager.GetString("LAYOUT_R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City - Row.
        /// </summary>
        public static string LAYOUT_R4 {
            get {
                return ResourceManager.GetString("LAYOUT_R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State - Row.
        /// </summary>
        public static string LAYOUT_R5 {
            get {
                return ResourceManager.GetString("LAYOUT_R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County - Row.
        /// </summary>
        public static string LAYOUT_R6 {
            get {
                return ResourceManager.GetString("LAYOUT_R6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code - Row.
        /// </summary>
        public static string LAYOUT_R7 {
            get {
                return ResourceManager.GetString("LAYOUT_R7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Offset.
        /// </summary>
        public static string LAYOUT_RowOffset {
            get {
                return ResourceManager.GetString("LAYOUT_RowOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 - Width.
        /// </summary>
        public static string LAYOUT_W1 {
            get {
                return ResourceManager.GetString("LAYOUT_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2 - Width.
        /// </summary>
        public static string LAYOUT_W2 {
            get {
                return ResourceManager.GetString("LAYOUT_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code - Width.
        /// </summary>
        public static string LAYOUT_W3 {
            get {
                return ResourceManager.GetString("LAYOUT_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City - Width.
        /// </summary>
        public static string LAYOUT_W4 {
            get {
                return ResourceManager.GetString("LAYOUT_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State - Width.
        /// </summary>
        public static string LAYOUT_W5 {
            get {
                return ResourceManager.GetString("LAYOUT_W5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County - Width.
        /// </summary>
        public static string LAYOUT_W6 {
            get {
                return ResourceManager.GetString("LAYOUT_W6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code - Width.
        /// </summary>
        public static string LAYOUT_W7 {
            get {
                return ResourceManager.GetString("LAYOUT_W7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog - Width.
        /// </summary>
        public static string LAYOUT_Width {
            get {
                return ResourceManager.GetString("LAYOUT_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one row for communication method &amp;0 and address ID &amp;1, but no Default per Method and Address selected. Do you want to continue?.
        /// </summary>
        public static string QUESTION_NotAddDefaultSet {
            get {
                return ResourceManager.GetString("QUESTION_NotAddDefaultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one row for communication method &amp;0, but no Default per Method selected. Do you want to continue?.
        /// </summary>
        public static string QUESTION_NotMethDefaultSet {
            get {
                return ResourceManager.GetString("QUESTION_NotMethDefaultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Methods.
        /// </summary>
        public static string TAB_NAME_CustomerInfoCommMethod {
            get {
                return ResourceManager.GetString("TAB_NAME_CustomerInfoCommMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string TAB_NAME_CustomerInfoContact {
            get {
                return ResourceManager.GetString("TAB_NAME_CustomerInfoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string TAB_NAME_Order {
            get {
                return ResourceManager.GetString("TAB_NAME_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string TAB_NAME_Payment {
            get {
                return ResourceManager.GetString("TAB_NAME_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Project.
        /// </summary>
        public static string TAB_NAME_Proj {
            get {
                return ResourceManager.GetString("TAB_NAME_Proj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Reporting Parameter.
        /// </summary>
        public static string TAB_NAME_ProjRepParam {
            get {
                return ResourceManager.GetString("TAB_NAME_ProjRepParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string TAB_NAME_Purch {
            get {
                return ResourceManager.GetString("TAB_NAME_Purch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Methods.
        /// </summary>
        public static string TAB_NAME_SupplierInfoCommMethod {
            get {
                return ResourceManager.GetString("TAB_NAME_SupplierInfoCommMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string TAB_NAME_SupplierInfoContact {
            get {
                return ResourceManager.GetString("TAB_NAME_SupplierInfoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create accounting currency &amp;0. Currency does not exist in source company &amp;1.
        /// </summary>
        public static string TEXT_AccCurrInfoMissing {
            get {
                return ResourceManager.GetString("TEXT_AccCurrInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Accounting Year in the user defined calendar may not be empty..
        /// </summary>
        public static string TEXT_AccYearNotNull {
            get {
                return ResourceManager.GetString("TEXT_AccYearNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Remove Company for &amp;0 is finished..
        /// </summary>
        public static string TEXT_Activate {
            get {
                return ResourceManager.GetString("TEXT_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact will be blocked for use as a new customer contact.
        ///Do you want to select the Blocked for Use in CRM box in Customer window for existing customer contacts?.
        /// </summary>
        public static string TEXT_BlockForUse1 {
            get {
                return ResourceManager.GetString("TEXT_BlockForUse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact will be blocked for use as a new customer contact..
        /// </summary>
        public static string TEXT_BlockForUse2 {
            get {
                return ResourceManager.GetString("TEXT_BlockForUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact will be blocked for use as a new supplier contact..
        /// </summary>
        public static string TEXT_BlockSuppContact {
            get {
                return ResourceManager.GetString("TEXT_BlockSuppContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm ID &amp;0 is connected to an AR customer contact entered in the Payment tab. Do you still want to modify Valid From date?.
        /// </summary>
        public static string TEXT_CannotChangeValidFromDate {
            get {
                return ResourceManager.GetString("TEXT_CannotChangeValidFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm ID &amp;0 is connected to an AP supplier contact entered in the Payment tab. Do you still want to modify Valid From date?.
        /// </summary>
        public static string TEXT_CannotChangeValidFromDateAp {
            get {
                return ResourceManager.GetString("TEXT_CannotChangeValidFromDateAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm ID &amp;0 is connected to an AR customer contact entered in the Payment tab. Do you still want to modify Valid To date?.
        /// </summary>
        public static string TEXT_CannotChangeValidToDate {
            get {
                return ResourceManager.GetString("TEXT_CannotChangeValidToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm ID &amp;0 is connected to an AP supplier contact entered in the Payment tab. Do you still want to modify Valid To date?.
        /// </summary>
        public static string TEXT_CannotChangeValidToDateAp {
            get {
                return ResourceManager.GetString("TEXT_CannotChangeValidToDateAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the delivery address type when an end customer is connected..
        /// </summary>
        public static string TEXT_CannotDelDelivAddr {
            get {
                return ResourceManager.GetString("TEXT_CannotDelDelivAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string TEXT_ColumnValidTextValid {
            get {
                return ResourceManager.GetString("TEXT_ColumnValidTextValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        public static string TEXT_ColumnValidTextWithdrawn {
            get {
                return ResourceManager.GetString("TEXT_ColumnValidTextWithdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to change the communication method because it is connected to an AR customer contact entered in the Payment tab..
        /// </summary>
        public static string TEXT_CommMethodExistARCContact {
            get {
                return ResourceManager.GetString("TEXT_CommMethodExistARCContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Company Template.
        /// </summary>
        public static string TEXT_CompanyTemplateImport {
            get {
                return ResourceManager.GetString("TEXT_CompanyTemplateImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By removing the company You may loose all valuable information related to the Company. Please confirm to delete!.
        /// </summary>
        public static string TEXT_ConfirmRemoveCompany {
            get {
                return ResourceManager.GetString("TEXT_ConfirmRemoveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By removing the company log you will delete all the information logged when the company were created. Please confirm to delete!.
        /// </summary>
        public static string TEXT_ConfirmRemoveCompanyLog {
            get {
                return ResourceManager.GetString("TEXT_ConfirmRemoveCompanyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Purpose Set.
        /// </summary>
        public static string TEXT_ConsentNew {
            get {
                return ResourceManager.GetString("TEXT_ConsentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Purposes.
        /// </summary>
        public static string TEXT_ConsentUpdate {
            get {
                return ResourceManager.GetString("TEXT_ConsentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors while synchronizing &amp;0. Do you want to refer basic data synchronization log for more details ?.
        /// </summary>
        public static string TEXT_CopiedError {
            get {
                return ResourceManager.GetString("TEXT_CopiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying a One-Time partner identity will not include all the address information and communication methods that are connected to the source identity. Do you want to continue?.
        /// </summary>
        public static string TEXT_CopyOneTimeIdentity {
            get {
                return ResourceManager.GetString("TEXT_CopyOneTimeIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &amp;0 is copied from template &amp;1..
        /// </summary>
        public static string TEXT_CopyTemplate {
            get {
                return ResourceManager.GetString("TEXT_CopyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Diff Template.
        /// </summary>
        public static string TEXT_CreateDiffTemplate {
            get {
                return ResourceManager.GetString("TEXT_CreateDiffTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Company.
        /// </summary>
        public static string TEXT_CreatingCompany {
            get {
                return ResourceManager.GetString("TEXT_CreatingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating in.
        /// </summary>
        public static string TEXT_CreatingIn {
            get {
                return ResourceManager.GetString("TEXT_CreatingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value in the Cust Stat Grp field is required for transferring order related data..
        /// </summary>
        public static string TEXT_CustGroupNullNotAllowed {
            get {
                return ResourceManager.GetString("TEXT_CustGroupNullNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer &amp;0 already exists. Enter another value or leave the field blank in order to generate a customer ID automatically..
        /// </summary>
        public static string TEXT_CustomerExist {
            get {
                return ResourceManager.GetString("TEXT_CustomerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs.
        /// </summary>
        public static string TEXT_CustomsPartyType {
            get {
                return ResourceManager.GetString("TEXT_CustomsPartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating purposes might result in removal of some personal data. Do you wish to continue?.
        /// </summary>
        public static string TEXT_DataPersonalConsentRevoke {
            get {
                return ResourceManager.GetString("TEXT_DataPersonalConsentRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating purposes will result in removal of following personal data: &amp;0. Do you wish to continue?.
        /// </summary>
        public static string TEXT_DataPersonalConsentRevokeParams {
            get {
                return ResourceManager.GetString("TEXT_DataPersonalConsentRevokeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default address ID already exists for &amp;0Address Type(s) for this time period. Do you want to set the current address ID as default instead?.
        /// </summary>
        public static string TEXT_DefAddressExt {
            get {
                return ResourceManager.GetString("TEXT_DefAddressExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address display layout will be reset to default. Are you sure you want to continue?.
        /// </summary>
        public static string TEXT_DefaultDisplay {
            get {
                return ResourceManager.GetString("TEXT_DefaultDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address edit layout will be reset to default. Are you sure you want to continue?.
        /// </summary>
        public static string TEXT_DefaultEdit {
            get {
                return ResourceManager.GetString("TEXT_DefaultEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the default &amp;0Address Type(s) for &amp;1 &amp;2. If removed, there will be no default address for this Address Type(s). Do you want to continue?.
        /// </summary>
        public static string TEXT_DefautExists {
            get {
                return ResourceManager.GetString("TEXT_DefautExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal of Temporary Diff Templates will take place, may take a while.
        /// </summary>
        public static string TEXT_DeleteTempDiffTemplates {
            get {
                return ResourceManager.GetString("TEXT_DeleteTempDiffTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An end customer has been connected and you cannot change the delivery address type..
        /// </summary>
        public static string TEXT_DelivAddrMustExist {
            get {
                return ResourceManager.GetString("TEXT_DelivAddrMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 is different from Detail Address..
        /// </summary>
        public static string TEXT_DiffAddrress1 {
            get {
                return ResourceManager.GetString("TEXT_DiffAddrress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship-via codes and delivery terms corresponding to the end customer&apos;s address identity &amp;0 will be used when saving the record..
        /// </summary>
        public static string TEXT_EndCustChanged {
            get {
                return ResourceManager.GetString("TEXT_EndCustChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while exporting the address display layout..
        /// </summary>
        public static string TEXT_ErrorExportDisplay {
            get {
                return ResourceManager.GetString("TEXT_ErrorExportDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while exporting the address edit layout..
        /// </summary>
        public static string TEXT_ErrorExportEdit {
            get {
                return ResourceManager.GetString("TEXT_ErrorExportEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while importing the address display layout..
        /// </summary>
        public static string TEXT_ErrorImportDisplay {
            get {
                return ResourceManager.GetString("TEXT_ErrorImportDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while importing the address edit layout..
        /// </summary>
        public static string TEXT_ErrorImportEdit {
            get {
                return ResourceManager.GetString("TEXT_ErrorImportEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove an Address line you have to enter 0 for value..
        /// </summary>
        public static string TEXT_ErrorNullAddress {
            get {
                return ResourceManager.GetString("TEXT_ErrorNullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder.
        /// </summary>
        public static string TEXT_ExportCompTemplToFile {
            get {
                return ResourceManager.GetString("TEXT_ExportCompTemplToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Template File(s).
        /// </summary>
        public static string TEXT_ExportTemplToFile {
            get {
                return ResourceManager.GetString("TEXT_ExportTemplToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file(s) are created..
        /// </summary>
        public static string TEXT_ExportToFile {
            get {
                return ResourceManager.GetString("TEXT_ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template File Name Is Mandatory.
        /// </summary>
        public static string TEXT_FileNameMissing {
            get {
                return ResourceManager.GetString("TEXT_FileNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Company is already created use Update Company instead..
        /// </summary>
        public static string TEXT_Finished {
            get {
                return ResourceManager.GetString("TEXT_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form of business ID &amp;0 is not valid for the country code &amp;1. Select a form of business that is connected to country code &amp;1 in the Forms of Business window..
        /// </summary>
        public static string TEXT_FormOfBusiness {
            get {
                return ResourceManager.GetString("TEXT_FormOfBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the Country Code will remove the current Form of Business, as it is country specific. Use the Customer window to enter a new Form of Business which is valid for the new Country Code..
        /// </summary>
        public static string TEXT_FormOfBusinessCustomer {
            get {
                return ResourceManager.GetString("TEXT_FormOfBusinessCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the Country Code will remove the current Form of Business, as it is country specific. Use the Supplier window to enter a new Form of Business which is valid for the new Country Code..
        /// </summary>
        public static string TEXT_FormOfBusinessSupplier {
            get {
                return ResourceManager.GetString("TEXT_FormOfBusinessSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &amp;0 is imported..
        /// </summary>
        public static string TEXT_ImportFile {
            get {
                return ResourceManager.GetString("TEXT_ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Template &amp;0 already exist. Do you want to replace the company template?.
        /// </summary>
        public static string TEXT_ImportFileExist {
            get {
                return ResourceManager.GetString("TEXT_ImportFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to overwrite Company Template &amp;0. Import process will be aborted..
        /// </summary>
        public static string TEXT_ImportFileNotAllowed {
            get {
                return ResourceManager.GetString("TEXT_ImportFileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installed versions of the component/s &amp;0 do not fully support create company from template or company. Note that this may cause inconsistency related errors during the process..
        /// </summary>
        public static string TEXT_Info {
            get {
                return ResourceManager.GetString("TEXT_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One-Time check box for customer &amp;0 cannot be modified due to the existing information in &amp;1..
        /// </summary>
        public static string TEXT_InvalidOneTimeCustomer {
            get {
                return ResourceManager.GetString("TEXT_InvalidOneTimeCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One-Time check box for supplier &amp;0 cannot be modified due to the existing information in &amp;1..
        /// </summary>
        public static string TEXT_InvalidOneTimeSupplier {
            get {
                return ResourceManager.GetString("TEXT_InvalidOneTimeSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start from Year must be equal to First Accounting Year or one year less..
        /// </summary>
        public static string TEXT_InvalidStartYear {
            get {
                return ResourceManager.GetString("TEXT_InvalidStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last address type(s) for address identity &amp;0 of &amp;1 &amp;2. If removed, there will not be any address type(s) for this address ID. Do you want to continue?.
        /// </summary>
        public static string TEXT_LastAddressType {
            get {
                return ResourceManager.GetString("TEXT_LastAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &amp;0 is imported with errors. Check Template Log Id:&amp;1.
        /// </summary>
        public static string TEXT_LogImportFile {
            get {
                return ResourceManager.GetString("TEXT_LogImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template files are imported with errors. Check Template Log Id:&amp;0.
        /// </summary>
        public static string TEXT_LogImportFile2 {
            get {
                return ResourceManager.GetString("TEXT_LogImportFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one record exists for the same Manager. Please enter the Manager Customer Address or use the list of values to select a Manager..
        /// </summary>
        public static string TEXT_ManyContactAddress {
            get {
                return ResourceManager.GetString("TEXT_ManyContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The templates are merged..
        /// </summary>
        public static string TEXT_MergeFileReady {
            get {
                return ResourceManager.GetString("TEXT_MergeFileReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Template File.
        /// </summary>
        public static string TEXT_MergeTemplToFile {
            get {
                return ResourceManager.GetString("TEXT_MergeTemplToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File name is invalid or write access denied..
        /// </summary>
        public static string TEXT_MergeWizWriteError {
            get {
                return ResourceManager.GetString("TEXT_MergeWizWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start Month must be two or above when the Start Year is one less than the First Accounting Year..
        /// </summary>
        public static string TEXT_MonthTooSmallForAccYear {
            get {
                return ResourceManager.GetString("TEXT_MonthTooSmallForAccYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allowed length for Full Name is 100 characters. The concatenated value of First Name, Middle Name and Last Name exceeds the limit..
        /// </summary>
        public static string TEXT_NameLengthNotAllowed {
            get {
                return ResourceManager.GetString("TEXT_NameLengthNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Diff Template Created, no differences exist between Company and Update Source.
        /// </summary>
        public static string TEXT_NoDiffTemplateCreated {
            get {
                return ResourceManager.GetString("TEXT_NoDiffTemplateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have privileges to method &apos;Person_Company_Access_API.New&apos; to complete the person creation process..
        /// </summary>
        public static string TEXT_NoPriviledge {
            get {
                return ResourceManager.GetString("TEXT_NoPriviledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Created with Error, check the Company Log..
        /// </summary>
        public static string TEXT_NoSuccess {
            get {
                return ResourceManager.GetString("TEXT_NoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Created with Error. Press Yes to open Company Log..
        /// </summary>
        public static string TEXT_NoSuccessOpenLog {
            get {
                return ResourceManager.GetString("TEXT_NoSuccessOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Updated with Error, check the Company Log..
        /// </summary>
        public static string TEXT_NoSuccessUpdate {
            get {
                return ResourceManager.GetString("TEXT_NoSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Updated with Error. Press Yes to open Company Log..
        /// </summary>
        public static string TEXT_NoSuccessUpdateOpenLog {
            get {
                return ResourceManager.GetString("TEXT_NoSuccessUpdateOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number given for the First Accounting Year is not valid..
        /// </summary>
        public static string TEXT_NotAValidAccYear {
            get {
                return ResourceManager.GetString("TEXT_NotAValidAccYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number given for the Start Year is not valid..
        /// </summary>
        public static string TEXT_NotAValidYear {
            get {
                return ResourceManager.GetString("TEXT_NotAValidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Years for the user defined calendar must be positive..
        /// </summary>
        public static string TEXT_NotPositiveYears {
            get {
                return ResourceManager.GetString("TEXT_NotPositiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to save the Invoice Tab before entering records to Payment Tab.
        /// </summary>
        public static string TEXT_NotSaved {
            get {
                return ResourceManager.GetString("TEXT_NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Years for the user defined calendar must be less than a hundred years..
        /// </summary>
        public static string TEXT_NotThreeDigitsYears {
            get {
                return ResourceManager.GetString("TEXT_NotThreeDigitsYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number given for the Start Month is not valid..
        /// </summary>
        public static string TEXT_NotWithinMonthRange {
            get {
                return ResourceManager.GetString("TEXT_NotWithinMonthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Years in the user defined calendar may not be empty..
        /// </summary>
        public static string TEXT_NumberOfYearsNotNull {
            get {
                return ResourceManager.GetString("TEXT_NumberOfYearsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From Date must be specified for Parallel Accounting Currency..
        /// </summary>
        public static string TEXT_Parallel {
            get {
                return ResourceManager.GetString("TEXT_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Currency is defined as same as the Accounting Currency. Do you want to continue?.
        /// </summary>
        public static string TEXT_ParallelAccNext {
            get {
                return ResourceManager.GetString("TEXT_ParallelAccNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Value for Parallel Currency Base.
        /// </summary>
        public static string TEXT_ParallelCurrBase {
            get {
                return ResourceManager.GetString("TEXT_ParallelCurrBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create parallel currency &amp;0. Currency does not exist in source company &amp;1.
        /// </summary>
        public static string TEXT_ParallelCurrInfoMissing {
            get {
                return ResourceManager.GetString("TEXT_ParallelCurrInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Component ENTERP is not allowed to have any Parent Component..
        /// </summary>
        public static string TEXT_ParentComponent {
            get {
                return ResourceManager.GetString("TEXT_ParentComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several &amp;0 were not synchronized to the target companies due to errors. Do you want to refer basic data synchronization log for more details ?.
        /// </summary>
        public static string TEXT_PartiallyCopied {
            get {
                return ResourceManager.GetString("TEXT_PartiallyCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Personal Data Property Codes.
        /// </summary>
        public static string TEXT_PersonalDataManPropertyCode {
            get {
                return ResourceManager.GetString("TEXT_PersonalDataManPropertyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Processing Purpose Configuration.
        /// </summary>
        public static string TEXT_ProcOfPersDataPurp {
            get {
                return ResourceManager.GetString("TEXT_ProcOfPersDataPurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Configuration.
        /// </summary>
        public static string TEXT_ProcOfPersDataPurpFromPurp {
            get {
                return ResourceManager.GetString("TEXT_ProcOfPersDataPurpFromPurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Action will delete all records in database related to the company. Do you really need to delete all these data?.
        /// </summary>
        public static string TEXT_RemoveCompany {
            get {
                return ResourceManager.GetString("TEXT_RemoveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &amp;0 is renamed to template &amp;1..
        /// </summary>
        public static string TEXT_RenameTemplate {
            get {
                return ResourceManager.GetString("TEXT_RenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning the file &amp;0 for template attributes is completed.
        /// </summary>
        public static string TEXT_ScanFile {
            get {
                return ResourceManager.GetString("TEXT_ScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark &amp;0 as the default template? ( The current default template will be de-selected.).
        /// </summary>
        public static string TEXT_SetDefault {
            get {
                return ResourceManager.GetString("TEXT_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Company/Template.
        /// </summary>
        public static string TEXT_SourceCompTempl {
            get {
                return ResourceManager.GetString("TEXT_SourceCompTempl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start Month in the user defined calendar may not be empty..
        /// </summary>
        public static string TEXT_StartMonthNotNull {
            get {
                return ResourceManager.GetString("TEXT_StartMonthNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Year in the user defined calendar may not be empty..
        /// </summary>
        public static string TEXT_StartYearNotNull {
            get {
                return ResourceManager.GetString("TEXT_StartYearNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Successfully Created..
        /// </summary>
        public static string TEXT_Success {
            get {
                return ResourceManager.GetString("TEXT_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected &amp;0 were successfully synchronized to the target companies..
        /// </summary>
        public static string TEXT_SuccessfullyCopied {
            get {
                return ResourceManager.GetString("TEXT_SuccessfullyCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Successfully Updated..
        /// </summary>
        public static string TEXT_SuccessUpdate {
            get {
                return ResourceManager.GetString("TEXT_SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Successfully Updated with some Comments, check the Company Log..
        /// </summary>
        public static string TEXT_SuccessUpdateComments {
            get {
                return ResourceManager.GetString("TEXT_SuccessUpdateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Office.
        /// </summary>
        public static string TEXT_TaxOficePartyType {
            get {
                return ResourceManager.GetString("TEXT_TaxOficePartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create accounting currency &amp;0. Currency does not exist in template &amp;1.
        /// </summary>
        public static string TEXT_TemAccCurrInfoMissing {
            get {
                return ResourceManager.GetString("TEXT_TemAccCurrInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create parallel currency &amp;0. Currency does not exist in template &amp;1.
        /// </summary>
        public static string TEXT_TemParallelCurrInfoMissing {
            get {
                return ResourceManager.GetString("TEXT_TemParallelCurrInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &amp;0 is created..
        /// </summary>
        public static string TEXT_TemplateCreated {
            get {
                return ResourceManager.GetString("TEXT_TemplateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template File(s) Imported.
        /// </summary>
        public static string TEXT_TemplateFileImport {
            get {
                return ResourceManager.GetString("TEXT_TemplateFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template information missing.
        /// </summary>
        public static string TEXT_TemplateInfoMissing {
            get {
                return ResourceManager.GetString("TEXT_TemplateInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact will be allowed (i.e., un-blocked) for use as a new customer contact.
        ///Do you want to clear the Blocked for Use in CRM box in Customer window for existing customer contacts?.
        /// </summary>
        public static string TEXT_UnBlockForUse1 {
            get {
                return ResourceManager.GetString("TEXT_UnBlockForUse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact will be allowed (i.e., un-blocked) for use as a new customer contact..
        /// </summary>
        public static string TEXT_UnBlockForUse2 {
            get {
                return ResourceManager.GetString("TEXT_UnBlockForUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact will be allowed (i.e., un-blocked) for use as a new supplier contact..
        /// </summary>
        public static string TEXT_UnblockSuppContact {
            get {
                return ResourceManager.GetString("TEXT_UnblockSuppContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Translations for Company: &amp;0.
        /// </summary>
        public static string TEXT_UpdateCompanyTranslation {
            get {
                return ResourceManager.GetString("TEXT_UpdateCompanyTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating in: &amp;0.
        /// </summary>
        public static string TEXT_UpdateCompanyTranslationIn {
            get {
                return ResourceManager.GetString("TEXT_UpdateCompanyTranslationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in.
        /// </summary>
        public static string TEXT_UpdateIn {
            get {
                return ResourceManager.GetString("TEXT_UpdateIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Company.
        /// </summary>
        public static string TEXT_UpdatingCompany {
            get {
                return ResourceManager.GetString("TEXT_UpdatingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined.
        /// </summary>
        public static string TEXT_UserDefined {
            get {
                return ResourceManager.GetString("TEXT_UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to mark template &amp;0 as a Valid template? This action will also change the version of each component in the template to the registered version. Note that this may cause 
        ///inconsistency related errors when using this template as source for the Create Company process..
        /// </summary>
        public static string TEXT_Valid {
            get {
                return ResourceManager.GetString("TEXT_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all mandatory fields are filled with values..
        /// </summary>
        public static string TEXT_Validate {
            get {
                return ResourceManager.GetString("TEXT_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Valid From of the Accounting Currency is not within the user defined calendar..
        /// </summary>
        public static string TEXT_ValidFromNotInCalendar {
            get {
                return ResourceManager.GetString("TEXT_ValidFromNotInCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another business partner with the same association number is already registered. Do you want to use the same Association No?.
        /// </summary>
        public static string TEXT_WarnSameAssocNo {
            get {
                return ResourceManager.GetString("TEXT_WarnSameAssocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards cannot be used for company name.
        /// </summary>
        public static string TEXT_Wildcard {
            get {
                return ResourceManager.GetString("TEXT_Wildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Customer Category.
        /// </summary>
        public static string TITLE_ChangeCustomerCategory {
            get {
                return ResourceManager.GetString("TITLE_ChangeCustomerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Address Display Layout.
        /// </summary>
        public static string TITLE_ExportDisplayLayout {
            get {
                return ResourceManager.GetString("TITLE_ExportDisplayLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Address Edit Layout.
        /// </summary>
        public static string TITLE_ExportEditLayout {
            get {
                return ResourceManager.GetString("TITLE_ExportEditLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Address Display Layout.
        /// </summary>
        public static string TITLE_ImportDisplayLayout {
            get {
                return ResourceManager.GetString("TITLE_ImportDisplayLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Address Edit Layout.
        /// </summary>
        public static string TITLE_ImportEditLayout {
            get {
                return ResourceManager.GetString("TITLE_ImportEditLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Attribute Translations.
        /// </summary>
        public static string WH_CompanyTranslation {
            get {
                return ResourceManager.GetString("WH_CompanyTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Company Template Assistant.
        /// </summary>
        public static string WH_Create {
            get {
                return ResourceManager.GetString("WH_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Templates.
        /// </summary>
        public static string WH_CreateCompanyTem {
            get {
                return ResourceManager.GetString("WH_CreateCompanyTem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Template Component.
        /// </summary>
        public static string WH_CreateCompanyTemComp {
            get {
                return ResourceManager.GetString("WH_CreateCompanyTemComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Template Detail.
        /// </summary>
        public static string WH_CreateCompanyTemDetail {
            get {
                return ResourceManager.GetString("WH_CreateCompanyTemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Template Lu.
        /// </summary>
        public static string WH_CreateCompanyTemLu {
            get {
                return ResourceManager.GetString("WH_CreateCompanyTemLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer Contact.
        /// </summary>
        public static string WH_dlgAddCustContact {
            get {
                return ResourceManager.GetString("WH_dlgAddCustContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier Contact.
        /// </summary>
        public static string WH_dlgAddSuppContact {
            get {
                return ResourceManager.GetString("WH_dlgAddSuppContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Company.
        /// </summary>
        public static string WH_dlgChangeCompany {
            get {
                return ResourceManager.GetString("WH_dlgChangeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Global Company.
        /// </summary>
        public static string WH_dlgChangeGlobalCompany {
            get {
                return ResourceManager.GetString("WH_dlgChangeGlobalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Format.
        /// </summary>
        public static string WH_dlgLayoutFormat {
            get {
                return ResourceManager.GetString("WH_dlgLayoutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Processing Purpose Management.
        /// </summary>
        public static string WH_dlgPersonalDataConsent {
            get {
                return ResourceManager.GetString("WH_dlgPersonalDataConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string WH_frmBranches {
            get {
                return ResourceManager.GetString("WH_frmBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string WH_frmCompany {
            get {
                return ResourceManager.GetString("WH_frmCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string WH_frmCustomer {
            get {
                return ResourceManager.GetString("WH_frmCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string WH_frmPerson {
            get {
                return ResourceManager.GetString("WH_frmPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons per Company.
        /// </summary>
        public static string WH_frmPersonsPerCompany {
            get {
                return ResourceManager.GetString("WH_frmPersonsPerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string WH_frmSupplier {
            get {
                return ResourceManager.GetString("WH_frmSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Address Information.
        /// </summary>
        public static string WH_frmSupplierInfoAddress {
            get {
                return ResourceManager.GetString("WH_frmSupplierInfoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Privileged to Remove Company.
        /// </summary>
        public static string WH_frmUserPrivRemoveCompany {
            get {
                return ResourceManager.GetString("WH_frmUserPrivRemoveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Company Template File Assistant.
        /// </summary>
        public static string WH_Import {
            get {
                return ResourceManager.GetString("WH_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Setup per Country.
        /// </summary>
        public static string WH_tbwAddressCountries {
            get {
                return ResourceManager.GetString("WH_tbwAddressCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string WH_tbwCompany {
            get {
                return ResourceManager.GetString("WH_tbwCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string WH_tbwCustomer {
            get {
                return ResourceManager.GetString("WH_tbwCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string WH_tbwSupplier {
            get {
                return ResourceManager.GetString("WH_tbwSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Liabilities.
        /// </summary>
        public static string WH_tbwTaxLiability {
            get {
                return ResourceManager.GetString("WH_tbwTaxLiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Attribute Translations.
        /// </summary>
        public static string WH_TemplateTranslation {
            get {
                return ResourceManager.GetString("WH_TemplateTranslation", resourceCulture);
            }
        }
    }
}
